const teamLogos = {
  ANA: require('../assets/images/logos/ANA.png'),
  UTA: require('../assets/images/logos/UTA.png'),
  BOS: require('../assets/images/logos/BOS.png'),
  BUF: require('../assets/images/logos/BUF.png'),
  CGY: require('../assets/images/logos/CGY.png'),
  CAR: require('../assets/images/logos/CAR.png'),
  CHI: require('../assets/images/logos/CHI.png'),
  COL: require('../assets/images/logos/COL.png'),
  CBJ: require('../assets/images/logos/CBJ.png'),
  DAL: require('../assets/images/logos/DAL.png'),
  DET: require('../assets/images/logos/DET.png'),
  EDM: require('../assets/images/logos/EDM.png'),
  FLA: require('../assets/images/logos/FLA.png'),
  LAK: require('../assets/images/logos/LAK.png'),
  MIN: require('../assets/images/logos/MIN.png'),
  MTL: require('../assets/images/logos/MTL.png'),
  NSH: require('../assets/images/logos/NSH.png'),
  NJD: require('../assets/images/logos/NJD.png'),
  NYI: require('../assets/images/logos/NYI.png'),
  NYR: require('../assets/images/logos/NYR.png'),
  OTT: require('../assets/images/logos/OTT.png'),
  PHI: require('../assets/images/logos/PHI.png'),
  PIT: require('../assets/images/logos/PIT.png'),
  SJS: require('../assets/images/logos/SJS.png'),
  SEA: require('../assets/images/logos/SEA.png'),
  STL: require('../assets/images/logos/STL.png'),
  TBL: require('../assets/images/logos/TBL.png'),
  TOR: require('../assets/images/logos/TOR.png'),
  VAN: require('../assets/images/logos/VAN.png'),
  VGK: require('../assets/images/logos/VGK.png'),
  WSH: require('../assets/images/logos/WSH.png'),
  WPG: require('../assets/images/logos/WPG.png'),
  DEFAULT: require('../assets/images/logos/NHL.png'), // Default placeholder
};

export default teamLogos;