const teamLogos = {
  ANA: require('./images/logos/ANA.png'),
  UTA: require('./images/logos/UTA.png'),
  BOS: require('./images/logos/BOS.png'),
  BUF: require('./images/logos/BUF.png'),
  CGY: require('./images/logos/CGY.png'),
  CAR: require('./images/logos/CAR.png'),
  CHI: require('./images/logos/CHI.png'),
  COL: require('./images/logos/COL.png'),
  CBJ: require('./images/logos/CBJ.png'),
  DAL: require('./images/logos/DAL.png'),
  DET: require('./images/logos/DET.png'),
  EDM: require('./images/logos/EDM.png'),
  FLA: require('./images/logos/FLA.png'),
  LAK: require('./images/logos/LAK.png'),
  MIN: require('./images/logos/MIN.png'),
  MTL: require('./images/logos/MTL.png'),
  NSH: require('./images/logos/NSH.png'),
  NJD: require('./images/logos/NJD.png'),
  NYI: require('./images/logos/NYI.png'),
  NYR: require('./images/logos/NYR.png'),
  OTT: require('./images/logos/OTT.png'),
  PHI: require('./images/logos/PHI.png'),
  PIT: require('./images/logos/PIT.png'),
  SJS: require('./images/logos/SJS.png'),
  SEA: require('./images/logos/SEA.png'),
  STL: require('./images/logos/STL.png'),
  TBL: require('./images/logos/TBL.png'),
  TOR: require('./images/logos/TOR.png'),
  VAN: require('./images/logos/VAN.png'),
  VGK: require('./images/logos/VGK.png'),
  WSH: require('./images/logos/WSH.png'),
  WPG: require('./images/logos/WPG.png'),
  DEFAULT: require('./images/logos/NHL.png'), // Default placeholder
};

export default teamLogos;